---
- name: "Cloning amazon-dash-mqtt"
  tags: clone-dash-listener
  become_user: pi
  git:
    dest: "/home/pi/amazon-dash-mqtt/"
    repo: https://github.com/vergissberlin/amazon-dash-mqtt.git

- name: "Configuring amazon-dash-mqtt"
  tags: configure-dash-listener
  become: pi
  copy:
    src: "{{ item }}"
    dest: "/home/pi/amazon-dash-mqtt/"
    owner: "pi"
    mode: 0744
  with_fileglob:
    - "../files/dash-listener-config.json"

- name: "Installing required libraries"
  shell: "npm install && sudo npm install pm2 -g"
  args:
    chdir: "/home/pi/amazon-dash-mqtt/"

- name: "Setting autostart for dash-listener"
  become: pi
  shell: "pm2 start app.js && pm2 startup"
  args:
    chdir: "/home/pi/amazon-dash-mqtt"
