---
- name: "Cloning amazon-dash-mqtt"
  tags: clone-dash-listener
  become_user: pi
  git:
    dest: /home/pi/dash-listener
    repo: https://github.com/vergissberlin/amazon-dash-mqtt.git

- name: "Configuring amazon-dash-mqtt"
  tags: configure-dash-listener
  copy:
    src: "{{ item }}"
    dest: "/home/pi/amazon-dash-mqtt"
    owner: "pi"
    mode: 0744
  with_fileglob:
    - "../files/dash-listener-config.json"

- name: "Installing required libraries"
  shell:
    chdir: "/home/pi/amazon-dash-mqtt"
    free_form: "npm install && sudo npm install pm2 -g"

- name: "Setting autostart for dash-listener"
  shell:
    chdir: "/home/pi/amazon-dash-mqtt"
    free_form: "pm2 start app.js && pm2 startup"
