---
- name: "Installing nvm"
  shell:
    free_form: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash"
  tags: nvm-install

- name: "Installing node"
  shell:
    free_form: "nvm install node && nvm use node"
  tags: install-node
