---
- name: "Installing nvm"
  become: true
  become_user: pi
  warn: false
  shell: "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash"
  tags: nvm-install

- name: "Installing libpcap"
  apt:
    name: libpcap-dev
    state: present

- name: "Installing node"
  become: yes
  become_user: pi
  shell: '. /home/pi/.nvm/nvm.sh && nvm install node'
  args:
    creates: "/home/pi/.nvm/versions/node"
    chdir: "/home/pi"
    executable: /bin/bash
  tags: install-node

- name: "Installing pm2"
  become: yes
  become_user: pi
  shell: "npm install pm2 -g"
