---
- name: "Download node sources"
  become: true
  become_user: pi
  shell: "curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -"
  tags: "install-node" 

- name: "Installing libpcap"
  apt:
    name: libpcap-dev
    state: present
  tags: "install-node" 

- name: "Installing node"
  become: yes
  become_user: pi
  shell: "apt install -y nodejs"
  args:
    chdir: "/home/pi"
    executable: /bin/bash
  tags: install-node

- name: "Installing pm2"
  become: yes
  become_user: pi
  shell: "npm install pm2 -g"
